### ISSUE TITLE
applicationId != packagename leads to 'Could not find a class for package'

### ISSUE THREAD

**Issue by McPo** [robolectric/robolectric-gradle-plugin#124]
I assume due to the change made in https://github.com/robolectric/robolectric-gradle-plugin/pull/49, the package is now set to the applicationId. Would it not make more sense to set it to 'package' from the AndroidManifest?

This creates an issue when an application has an applicationId which does not match the package.
ie In my current project the applicationId is 'domain.com.application', while the package is 'com.domain.application'

Essentially the applicationId was originally a typo but since having been uploaded to the play store, I am unable to change it now. Below is the error I get, if I set the applicationId to the package, it resolved the issue (Although this isn't a permanent fix)

```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: Could not find a class for package: *****.com.***** and class name: .*****Application
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:226)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Could not find a class for package: *******.com.******* and class name: .*******Application
	at org.robolectric.DefaultTestLifecycle.createApplication(DefaultTestLifecycle.java:58)
	at org.robolectric.DefaultTestLifecycle.createApplication(DefaultTestLifecycle.java:14)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:92)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:440)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:222)
	... 35 more
Caused by: java.lang.ClassNotFoundException: Could not find a class for package: *******.com.****** and class name: .******Application
	at org.robolectric.internal.ClassNameResolver.resolve(ClassNameResolver.java:25)
	at org.robolectric.DefaultTestLifecycle.createApplication(DefaultTestLifecycle.java:56)
	... 39 more
```

Temporarily resolved it using

```
    tasks.withType(Test).whenTaskAdded {
        project.android.defaultConfig.applicationId 'com.*******.******'
    }
```

**Comment by erd** [comment]
The plugin is being deprecated with the release of Robolectric 3.0. Closing open issues.
