### ISSUE TITLE
Issues when mocking Canvas

### ISSUE THREAD

**Issue by danoz73** [robolectric/robolectric-gradle-plugin#145]
Just upgraded from `0.14.1` to `1.0.1` with the new `1.1.0` Android-Gradle-Plugin, and we are now having issues mocking the Android Canvas class. Everything is building smoothly, but tests run with mock canvases (tried mocking with Mockito `1.9.5` and `1.10.19`) yield a `NoClassDefFoundError` in openGL:

```java
    java.lang.NoClassDefFoundError: javax/microedition/khronos/opengles/GL
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2531)
        at java.lang.Class.getDeclaredMethods(Class.java:1855)
        at org.mockito.cglib.core.ReflectUtils.addAllMethods(ReflectUtils.java:349)
        at org.mockito.cglib.proxy.Enhancer.getMethods(Enhancer.java:422)
        at org.mockito.cglib.proxy.Enhancer.generateClass(Enhancer.java:457)
        at org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
        at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:217)
        at org.mockito.cglib.proxy.Enhancer.createHelper(Enhancer.java:378)
        at org.mockito.cglib.proxy.Enhancer.createClass(Enhancer.java:318)
        at org.mockito.internal.creation.cglib.ClassImposterizer.createProxyClass(ClassImposterizer.java:123)
        at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:57)
        at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:49)
        at org.mockito.internal.creation.cglib.CglibMockMaker.createMock(CglibMockMaker.java:24)
        at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
        at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
        at org.mockito.Mockito.mock(Mockito.java:1285)
        at org.mockito.Mockito.mock(Mockito.java:1163)
```
Here is the line on which the test fails:
```java
Canvas canvas = mock(Canvas.class);
```
Before attempting to upgrade, we had no issues mocking `android.graphics.Canvas` in our tests. Any help is appreciated.

Thanks!

**Comment by emerssso** [comment]
I am seeing this issue as well. We don't use the Robolectric plugin though, so I don't know if that is the source.  Mocks of Canvas seem to work correctly when the tests are run from Android studio (Ctrl-Shift-R on a Mac), but fail in command line. That will be a problem for our CI server.

**Comment by kageiit** [comment]
I solved this by creating the class in my test sources

```java
package javax.microedition.khronos.opengles;

public interface  GL { }

```

**Comment by haffax** [comment]
Thanks kageiit for the work-around. Solves it for us too, but still would be interesting to understand what exactly triggered this behaviour change.

**Comment by mpost** [comment]
We are seeing the same problem in 3.0-RC3.

**Comment by erd** [comment]
The plugin is being deprecated with the release of Robolectric 3.0. Closing open issues.
