### ISSUE TITLE
Cannot invoke method systemProperty() on null object

### ISSUE THREAD

**Issue by tomrozb** [robolectric/robolectric-gradle-plugin#160]
This issue occurs with `com.android.tools.build:gradle:1.3.0-beta3` it doesn't occur with `com.android.tools.build:gradle:1.3.0-beta1`

```
Caused by: java.lang.NullPointerException: Cannot invoke method systemProperty() on null object
	at org.robolectric.gradle.RobolectricPlugin$_apply_closure1_closure2.doCall(RobolectricPlugin.groovy:31)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:63)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
	at org.gradle.api.DomainObjectCollection$all$1.call(Unknown Source)
	at org.robolectric.gradle.RobolectricPlugin$_apply_closure1.doCall(RobolectricPlugin.groovy:27)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy13.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:79)
	... 38 more
```

**Comment by erd** [comment]
This plugin has not been updated to support 1.3.0. Also, once Robolectric 3.0 is released, this plugin will be deprecated (since it is not required to run tests with newer versions 1.2.0+ of the android gradle plugin).

**Comment by erd** [comment]
The plugin is being deprecated with the release of Robolectric 3.0. Closing open issues.
